Support non-ROTD tarball filenames.
Prompted by patch by Xiaofeng Yang

diff --git a/make_rpm b/make_rpm
--- a/make_rpm
+++ b/make_rpm
@@ -13,17 +13,23 @@ then
     exit 1
 fi
 
-version=$( basename $tarball )
-version=${version%.tar.*}
-version=${version#mercury-*-}
+base=$( basename $tarball )
+base=${base%.tar.*}
+version=${base#mercury-srcdist-}
 case $version in
     rotd-2[0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9])
         ;;
+    [0-9][0-9]*-beta-*)
+        ;;
+    [0-9][0-9].[0-9][0-9]*)
+        ;;
     *)
-        echo "Could not extracting version from filename: $tarball" 1>&2
+        echo "Could not extract version from filename: $tarball" 1>&2
         exit 1
         ;;
 esac
+
+echo "Version $version"
 
 version_with_underscores=${version//-/_}
 
