Rename make_debian_package to make_deb.

diff --git a/make_deb b/make_deb
--- a/make_deb
+++ b/make_deb
@@ -21,7 +21,7 @@ case $version in
     2[0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9])
         ;;
     *)
-        echo "Could not extracting version from filename: $tarball" 1>&2
+        echo "Could not extract version from filename: $tarball" 1>&2
         exit 1
         ;;
 esac
